version: '3.8'

services:
  kinetic-dex:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kinetic_dex_app
    expose:
      - "80"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/"]
      interval: 15s
      timeout: 5s
      retries: 3
